# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_bilbil.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello_bilbil.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12hello_bilbil.proto\x12\x04test\"(\n\x0bHelloDyqReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\":\n\rHelloDyqReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\"\xfe\x01\n\x0cHelloTestReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t\x12(\n\x03num\x18\x04 \x03(\x0b\x32\x1b.test.HelloTestReq.NumEntry\x1a\x45\n\x15HelloTestReqNumValues\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x11\n\tis_active\x18\x03 \x01(\x08\x1aT\n\x08NumEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.test.HelloTestReq.HelloTestReqNumValues:\x02\x38\x01\"\x10\n\x0eHelloTestReply\"\x1e\n\x0eHelloBoyCliReq\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\"\n\x10HelloBoyCliReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1c\n\x0cHelloSendReq\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\" \n\x0eHelloSendReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1e\n\x0eTestTwoWaysReq\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"%\n\x13TestTwoWaysResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x80\x02\n\x06\x42ilbil\x12\x34\n\x08HelloDyq\x12\x11.test.HelloDyqReq\x1a\x13.test.HelloDyqReply\"\x00\x12?\n\x0bHelloBoyCli\x12\x14.test.HelloBoyCliReq\x1a\x16.test.HelloBoyCliReply\"\x00\x30\x01\x12\x39\n\tHelloSend\x12\x12.test.HelloSendReq\x1a\x14.test.HelloSendReply\"\x00(\x01\x12\x44\n\x0bTestTwoWays\x12\x14.test.TestTwoWaysReq\x1a\x19.test.TestTwoWaysResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)




_HELLODYQREQ = _descriptor.Descriptor(
  name='HelloDyqReq',
  full_name='test.HelloDyqReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test.HelloDyqReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='test.HelloDyqReq.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=68,
)


_HELLODYQREPLY = _descriptor.Descriptor(
  name='HelloDyqReply',
  full_name='test.HelloDyqReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='test.HelloDyqReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='test.HelloDyqReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='test.HelloDyqReply.result', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=128,
)


_HELLOTESTREQ_HELLOTESTREQNUMVALUES = _descriptor.Descriptor(
  name='HelloTestReqNumValues',
  full_name='test.HelloTestReq.HelloTestReqNumValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test.HelloTestReq.HelloTestReqNumValues.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='test.HelloTestReq.HelloTestReqNumValues.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_active', full_name='test.HelloTestReq.HelloTestReqNumValues.is_active', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=299,
)

_HELLOTESTREQ_NUMENTRY = _descriptor.Descriptor(
  name='NumEntry',
  full_name='test.HelloTestReq.NumEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='test.HelloTestReq.NumEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='test.HelloTestReq.NumEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=385,
)

_HELLOTESTREQ = _descriptor.Descriptor(
  name='HelloTestReq',
  full_name='test.HelloTestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test.HelloTestReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='test.HelloTestReq.age', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='test.HelloTestReq.data', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num', full_name='test.HelloTestReq.num', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_HELLOTESTREQ_HELLOTESTREQNUMVALUES, _HELLOTESTREQ_NUMENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=385,
)


_HELLOTESTREPLY = _descriptor.Descriptor(
  name='HelloTestReply',
  full_name='test.HelloTestReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=403,
)


_HELLOBOYCLIREQ = _descriptor.Descriptor(
  name='HelloBoyCliReq',
  full_name='test.HelloBoyCliReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='test.HelloBoyCliReq.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=435,
)


_HELLOBOYCLIREPLY = _descriptor.Descriptor(
  name='HelloBoyCliReply',
  full_name='test.HelloBoyCliReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='test.HelloBoyCliReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=471,
)


_HELLOSENDREQ = _descriptor.Descriptor(
  name='HelloSendReq',
  full_name='test.HelloSendReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='test.HelloSendReq.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=501,
)


_HELLOSENDREPLY = _descriptor.Descriptor(
  name='HelloSendReply',
  full_name='test.HelloSendReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='test.HelloSendReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=535,
)


_TESTTWOWAYSREQ = _descriptor.Descriptor(
  name='TestTwoWaysReq',
  full_name='test.TestTwoWaysReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='test.TestTwoWaysReq.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=567,
)


_TESTTWOWAYSRESPONSE = _descriptor.Descriptor(
  name='TestTwoWaysResponse',
  full_name='test.TestTwoWaysResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='test.TestTwoWaysResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=569,
  serialized_end=606,
)

_HELLOTESTREQ_HELLOTESTREQNUMVALUES.containing_type = _HELLOTESTREQ
_HELLOTESTREQ_NUMENTRY.fields_by_name['value'].message_type = _HELLOTESTREQ_HELLOTESTREQNUMVALUES
_HELLOTESTREQ_NUMENTRY.containing_type = _HELLOTESTREQ
_HELLOTESTREQ.fields_by_name['num'].message_type = _HELLOTESTREQ_NUMENTRY
DESCRIPTOR.message_types_by_name['HelloDyqReq'] = _HELLODYQREQ
DESCRIPTOR.message_types_by_name['HelloDyqReply'] = _HELLODYQREPLY
DESCRIPTOR.message_types_by_name['HelloTestReq'] = _HELLOTESTREQ
DESCRIPTOR.message_types_by_name['HelloTestReply'] = _HELLOTESTREPLY
DESCRIPTOR.message_types_by_name['HelloBoyCliReq'] = _HELLOBOYCLIREQ
DESCRIPTOR.message_types_by_name['HelloBoyCliReply'] = _HELLOBOYCLIREPLY
DESCRIPTOR.message_types_by_name['HelloSendReq'] = _HELLOSENDREQ
DESCRIPTOR.message_types_by_name['HelloSendReply'] = _HELLOSENDREPLY
DESCRIPTOR.message_types_by_name['TestTwoWaysReq'] = _TESTTWOWAYSREQ
DESCRIPTOR.message_types_by_name['TestTwoWaysResponse'] = _TESTTWOWAYSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloDyqReq = _reflection.GeneratedProtocolMessageType('HelloDyqReq', (_message.Message,), {
  'DESCRIPTOR' : _HELLODYQREQ,
  '__module__' : 'hello_bilbil_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloDyqReq)
  })
_sym_db.RegisterMessage(HelloDyqReq)

HelloDyqReply = _reflection.GeneratedProtocolMessageType('HelloDyqReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLODYQREPLY,
  '__module__' : 'hello_bilbil_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloDyqReply)
  })
_sym_db.RegisterMessage(HelloDyqReply)

HelloTestReq = _reflection.GeneratedProtocolMessageType('HelloTestReq', (_message.Message,), {

  'HelloTestReqNumValues' : _reflection.GeneratedProtocolMessageType('HelloTestReqNumValues', (_message.Message,), {
    'DESCRIPTOR' : _HELLOTESTREQ_HELLOTESTREQNUMVALUES,
    '__module__' : 'hello_bilbil_pb2'
    # @@protoc_insertion_point(class_scope:test.HelloTestReq.HelloTestReqNumValues)
    })
  ,

  'NumEntry' : _reflection.GeneratedProtocolMessageType('NumEntry', (_message.Message,), {
    'DESCRIPTOR' : _HELLOTESTREQ_NUMENTRY,
    '__module__' : 'hello_bilbil_pb2'
    # @@protoc_insertion_point(class_scope:test.HelloTestReq.NumEntry)
    })
  ,
  'DESCRIPTOR' : _HELLOTESTREQ,
  '__module__' : 'hello_bilbil_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloTestReq)
  })
_sym_db.RegisterMessage(HelloTestReq)
_sym_db.RegisterMessage(HelloTestReq.HelloTestReqNumValues)
_sym_db.RegisterMessage(HelloTestReq.NumEntry)

HelloTestReply = _reflection.GeneratedProtocolMessageType('HelloTestReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOTESTREPLY,
  '__module__' : 'hello_bilbil_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloTestReply)
  })
_sym_db.RegisterMessage(HelloTestReply)

HelloBoyCliReq = _reflection.GeneratedProtocolMessageType('HelloBoyCliReq', (_message.Message,), {
  'DESCRIPTOR' : _HELLOBOYCLIREQ,
  '__module__' : 'hello_bilbil_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloBoyCliReq)
  })
_sym_db.RegisterMessage(HelloBoyCliReq)

HelloBoyCliReply = _reflection.GeneratedProtocolMessageType('HelloBoyCliReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOBOYCLIREPLY,
  '__module__' : 'hello_bilbil_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloBoyCliReply)
  })
_sym_db.RegisterMessage(HelloBoyCliReply)

HelloSendReq = _reflection.GeneratedProtocolMessageType('HelloSendReq', (_message.Message,), {
  'DESCRIPTOR' : _HELLOSENDREQ,
  '__module__' : 'hello_bilbil_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloSendReq)
  })
_sym_db.RegisterMessage(HelloSendReq)

HelloSendReply = _reflection.GeneratedProtocolMessageType('HelloSendReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOSENDREPLY,
  '__module__' : 'hello_bilbil_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloSendReply)
  })
_sym_db.RegisterMessage(HelloSendReply)

TestTwoWaysReq = _reflection.GeneratedProtocolMessageType('TestTwoWaysReq', (_message.Message,), {
  'DESCRIPTOR' : _TESTTWOWAYSREQ,
  '__module__' : 'hello_bilbil_pb2'
  # @@protoc_insertion_point(class_scope:test.TestTwoWaysReq)
  })
_sym_db.RegisterMessage(TestTwoWaysReq)

TestTwoWaysResponse = _reflection.GeneratedProtocolMessageType('TestTwoWaysResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTTWOWAYSRESPONSE,
  '__module__' : 'hello_bilbil_pb2'
  # @@protoc_insertion_point(class_scope:test.TestTwoWaysResponse)
  })
_sym_db.RegisterMessage(TestTwoWaysResponse)


_HELLOTESTREQ_NUMENTRY._options = None

_BILBIL = _descriptor.ServiceDescriptor(
  name='Bilbil',
  full_name='test.Bilbil',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=609,
  serialized_end=865,
  methods=[
  _descriptor.MethodDescriptor(
    name='HelloDyq',
    full_name='test.Bilbil.HelloDyq',
    index=0,
    containing_service=None,
    input_type=_HELLODYQREQ,
    output_type=_HELLODYQREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HelloBoyCli',
    full_name='test.Bilbil.HelloBoyCli',
    index=1,
    containing_service=None,
    input_type=_HELLOBOYCLIREQ,
    output_type=_HELLOBOYCLIREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HelloSend',
    full_name='test.Bilbil.HelloSend',
    index=2,
    containing_service=None,
    input_type=_HELLOSENDREQ,
    output_type=_HELLOSENDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TestTwoWays',
    full_name='test.Bilbil.TestTwoWays',
    index=3,
    containing_service=None,
    input_type=_TESTTWOWAYSREQ,
    output_type=_TESTTWOWAYSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BILBIL)

DESCRIPTOR.services_by_name['Bilbil'] = _BILBIL

# @@protoc_insertion_point(module_scope)
